### PR TITLE
create branching rules

### PR DESCRIPTION
**Pull request by abizzaar**
1. I had to rename "local" to "locals" because local is a keyword used to initialize local variables.
2. I know I initially suggested hiding store/context modifications behind metafunctions, but after working on the codebase I feel it will be better as many modifications as possible in the rules itself to prevent an unnecessary amount of scrolling (especially when the metafunction isn't reusable).
3. Note that for functions, blocks and loops we are simply leaving the instruction stack polluted with all values instead of only leaving the return values on the stack. All of these generally have a "function signature" associated but we can talk more about our simplified approach in a meeting.
4. The paper does not specify what to do when we have (br 10) and there aren't 10 blocks in outer scope. Right now we just use the debug-inst for this.

### CODE REVIEW

**Review by a-r-n — APPROVED** [review]

**Comment by a-r-n** [comment]
I think branching out of bounds should trigger `trap`

**Comment by abizzaar** [comment]
It does feel like something that could be statically verifiable and doesn't need to produce a runtime error. From my understanding, our favorite WASM explorer prevents compilation with the error "branch depth exceeds current nesting level"

**Comment by a-r-n** [comment]
Ok, I'm fine ignoring it then or doing what you've done

**Comment by abizzaar** [comment]
@domisky2003 feel free to still suggest revisions and I'll incorporate them in another pull request

**Pull request merged**
